[package]
name = "ailoom-fs"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
ailoom-core = { path = "../ailoom-core" }
ignore = "0.4"
walkdir = "2"
percent-encoding = "2"
pathdiff = "0.2"
sha2 = "0.10"
hex = "0.4"
