// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main entity model - replace with your actual entity
 */
export type Entity = { id: string, name: string, description: string | null, created_at: string, updated_at: string, };
