// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification sent from the client to the server.
 */
export type ClientNotification = { "method": "initialized" };
