// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId";

export type ConversationSummary = { conversationId: ConversationId, path: string, preview: string, 
/**
 * RFC3339 timestamp string for the session start, if available.
 */
timestamp: string | null, };
