// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId";

/**
 * Response payload for `Op::GetHistory` containing the current session's
 * in-memory transcript.
 */
export type ConversationPathResponseEvent = { conversation_id: ConversationId, path: string, };
