// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedCommand } from "./ParsedCommand";

export type ExecApprovalRequestEvent = { 
/**
 * Identifier for the associated exec call, if available.
 */
call_id: string, 
/**
 * The command to be executed.
 */
command: Array<string>, 
/**
 * The command's working directory.
 */
cwd: string, 
/**
 * Optional human-readable reason for the approval (e.g. retry without sandbox).
 */
reason: string | null, parsed_cmd: Array<ParsedCommand>, };
