// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SandboxPolicy } from "./SandboxPolicy";

export type ExecOneOffCommandParams = { 
/**
 * Command argv to execute.
 */
command: Array<string>, 
/**
 * Timeout of the command in milliseconds.
 * If not specified, a sensible default is used server-side.
 */
timeoutMs: bigint | null, 
/**
 * Optional working directory for the process. Defaults to server config cwd.
 */
cwd: string | null, 
/**
 * Optional explicit sandbox policy overriding the server default.
 */
sandboxPolicy: SandboxPolicy | null, };
