// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetAuthStatusParams = { 
/**
 * If true, include the current auth token (if available) in the response.
 */
includeToken: boolean | null, 
/**
 * If true, attempt to refresh the token before returning status.
 */
refreshToken: boolean | null, };
