// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InputItem = { "type": "text", "data": { text: string, } } | { "type": "image", "data": { image_url: string, } } | { "type": "localImage", "data": { path: string, } };
