// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskForApproval } from "./AskForApproval";
import type { SandboxMode } from "./SandboxMode";
import type { JsonValue } from "./serde_json/JsonValue";

export type NewConversationParams = { 
/**
 * Optional override for the model name (e.g. "o3", "o4-mini").
 */
model: string | null, 
/**
 * Configuration profile from config.toml to specify default options.
 */
profile: string | null, 
/**
 * Working directory for the session. If relative, it is resolved against
 * the server process's current working directory.
 */
cwd: string | null, 
/**
 * Approval policy for shell commands generated by the model:
 * `untrusted`, `on-failure`, `on-request`, `never`.
 */
approvalPolicy: AskForApproval | null, 
/**
 * Sandbox mode: `read-only`, `workspace-write`, or `danger-full-access`.
 */
sandbox: SandboxMode | null, 
/**
 * Individual config settings that will override what is in
 * CODEX_HOME/config.toml.
 */
config: { [key in string]?: JsonValue } | null, 
/**
 * The set of instructions to use instead of the default ones.
 */
baseInstructions: string | null, 
/**
 * Whether to include the plan tool in the conversation.
 */
includePlanTool: boolean | null, 
/**
 * Whether to include the apply patch tool in the conversation.
 */
includeApplyPatchTool: boolean | null, };
