// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId";
import type { ReasoningEffort } from "./ReasoningEffort";

export type NewConversationResponse = { conversationId: ConversationId, model: string, 
/**
 * Note this could be ignored by the model.
 */
reasoningEffort: ReasoningEffort | null, rolloutPath: string, };
