// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RateLimitWindow = { 
/**
 * Percentage (0-100) of the window that has been consumed.
 */
used_percent: number, 
/**
 * Rolling window duration, in minutes.
 */
window_minutes: number | null, 
/**
 * Seconds until the window resets.
 */
resets_in_seconds: number | null, };
