// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotations } from "./Annotations";

/**
 * A known resource that the server is capable of reading.
 */
export type Resource = { annotations?: Annotations | null, description?: string | null, mimeType?: string | null, name: string, size?: bigint | null, title?: string | null, uri: string, };
