// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewConversationParams } from "./NewConversationParams";

export type ResumeConversationParams = { 
/**
 * Absolute path to the rollout JSONL file.
 */
path: string, 
/**
 * Optional overrides to apply when spawning the resumed session.
 */
overrides: NewConversationParams | null, };
