// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User's decision in response to an ExecApprovalRequest.
 */
export type ReviewDecision = "approved" | "approved_for_session" | "denied" | "abort";
