// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationId } from "./ConversationId";
import type { InputItem } from "./InputItem";

export type SendUserMessageParams = { conversationId: ConversationId, items: Array<InputItem>, };
