// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "./ReasoningEffort";

export type SetDefaultModelParams = { 
/**
 * If set to None, this means `model` should be cleared in config.toml.
 */
model: string | null, 
/**
 * If set to None, this means `model_reasoning_effort` should be cleared
 * in config.toml.
 */
reasoningEffort: ReasoningEffort | null, };
