// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MCP representation of a [`codex_core::config::ToolsToml`].
 */
export type Tools = { webSearch: boolean | null, viewImage: boolean | null, };
