// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AskForApproval } from "./AskForApproval";
import type { Profile } from "./Profile";
import type { ReasoningEffort } from "./ReasoningEffort";
import type { ReasoningSummary } from "./ReasoningSummary";
import type { SandboxMode } from "./SandboxMode";
import type { SandboxSettings } from "./SandboxSettings";
import type { Tools } from "./Tools";
import type { Verbosity } from "./Verbosity";

/**
 * UserSavedConfig contains a subset of the config. It is meant to expose mcp
 * client-configurable settings that can be specified in the NewConversation
 * and SendUserTurn requests.
 */
export type UserSavedConfig = { 
/**
 * Approvals
 */
approvalPolicy: AskForApproval | null, sandboxMode: SandboxMode | null, sandboxSettings: SandboxSettings | null, 
/**
 * Model-specific configuration
 */
model: string | null, modelReasoningEffort: ReasoningEffort | null, modelReasoningSummary: ReasoningSummary | null, modelVerbosity: Verbosity | null, 
/**
 * Tools
 */
tools: Tools | null, 
/**
 * Profiles
 */
profile: string | null, profiles: { [key in string]?: Profile }, };
