// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserInfoResponse = { 
/**
 * Note: `alleged_user_email` is not currently verified. We read it from
 * the local auth.json, which the user could theoretically modify. In the
 * future, we may add logic to verify the email against the server before
 * returning it.
 */
allegedUserEmail: string | null, };
